# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_member_reply_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='action_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='youtube_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
