# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160924_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video_queue',
            field=models.TextField(default=''),
        ),
    ]
